<a href="https://colab.research.google.com/github/Carinaaa/ML-Learning-Path/blob/intro-pandas/Data_Exploration_Students_earnings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd

In [31]:
student_data = pd.read_csv('salaries_by_college_major.csv')
student_data.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [32]:
# How many rows are there?
student_data.shape

(51, 6)

In [33]:
# Data cleaning
student_data.isna().sum()

Undergraduate Major                  0
Starting Median Salary               1
Mid-Career Median Salary             1
Mid-Career 10th Percentile Salary    1
Mid-Career 90th Percentile Salary    1
Group                                1
dtype: int64

In [34]:
clean_student_data = student_data.dropna()
clean_student_data.isna().sum()

Undergraduate Major                  0
Starting Median Salary               0
Mid-Career Median Salary             0
Mid-Career 10th Percentile Salary    0
Mid-Career 90th Percentile Salary    0
Group                                0
dtype: int64

In [35]:
# Find College Major with Highest Starting Salaries
max_salary = clean_student_data['Starting Median Salary'].max()
id_max_salary = clean_student_data['Starting Median Salary'].idxmax()
job_max_salaray = clean_student_data["Undergraduate Major"][id_max_salary]
max_salary, job_max_salaray

(74300.0, 'Physician Assistant')

In [36]:
clean_student_data.loc[id_max_salary]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [37]:
# What college major has the highest mid-career salary?

id_max_mid = clean_student_data["Mid-Career Median Salary"].idxmax()
clean_student_data.loc[id_max_mid]

Undergraduate Major                  Chemical Engineering
Starting Median Salary                            63200.0
Mid-Career Median Salary                         107000.0
Mid-Career 10th Percentile Salary                 71900.0
Mid-Career 90th Percentile Salary                194000.0
Group                                                STEM
Name: 8, dtype: object

In [38]:
# Which college major has the lowest starting salary and how much do graduates earn after university?

id_min_start = clean_student_data["Starting Median Salary"].idxmax()
mid_starting = clean_student_data.loc[id_min_start]
collage_major = mid_starting["Undergraduate Major"]
min_starting = mid_starting["Mid-Career Median Salary"]
collage_major, min_starting

('Physician Assistant', np.float64(91700.0))

In [39]:
# Which college major has the lowest mid-career salary and how much can people expect to earn with this degree?

low_mid = clean_student_data["Mid-Career Median Salary"].idxmin()
mid_low = clean_student_data["Undergraduate Major"].loc[low_mid]
mid_low

'Education'

In [40]:
# Lowest Risk Majors
risk = clean_student_data["Mid-Career 90th Percentile Salary"] - clean_student_data["Mid-Career 10th Percentile Salary"]
# Using substract
risk_sub = clean_student_data["Mid-Career 90th Percentile Salary"].subtract(clean_student_data["Mid-Career 10th Percentile Salary"])
risk.head(), risk_sub.head()

(0    109800.0
 1     96700.0
 2    113700.0
 3    104200.0
 4     85400.0
 dtype: float64,
 0    109800.0
 1     96700.0
 2    113700.0
 3    104200.0
 4     85400.0
 dtype: float64)

In [41]:
clean_student_data.insert(1, "Risk", risk)
clean_student_data.head()

,Undergraduate Major,Risk,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [42]:
# Sorting by the Lowest Spread
sorted_risk = clean_student_data.sort_values("Risk")
sorted_risk[["Undergraduate Major", "Risk"]].head()

           Undergraduate Major     Risk
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [43]:
# Sorting highest risk
desc_sorted_risk = clean_student_data.sort_values("Risk", ascending=False)
desc_sorted_risk[["Undergraduate Major", "Risk"]].head()

   Undergraduate Major      Risk
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [44]:
# Highest potential
high_pot = clean_student_data.sort_values("Mid-Career 90th Percentile Salary", ascending=False)
high_pot[["Undergraduate Major", "Mid-Career 90th Percentile Salary"]].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [48]:
# Grouping and Pivoting Data
count_group = clean_student_data.groupby("Group").count()
count_group

,Undergraduate Major,Risk,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [50]:
clean_student_data.head()

,Undergraduate Major,Risk,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [55]:
clean_student_data.groupby("Group")[["Starting Median Salary", "Mid-Career Median Salary", "Mid-Career 10th Percentile Salary", "Mid-Career 90th Percentile Salary", "Risk"]].mean()

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Risk
Group,,,,,
Business,44633.333333,75083.333333,43566.666667,147525.000000,103958.333333
HASS,37186.363636,62968.181818,34145.454545,129363.636364,95218.181818
STEM,53862.500000,90812.500000,56025.000000,157625.000000,101600.000000

In [56]:
pd.options.display.float_format = '{:,.2f}'.format
clean_student_data.groupby("Group")[["Starting Median Salary", "Mid-Career Median Salary", "Mid-Career 10th Percentile Salary", "Mid-Career 90th Percentile Salary", "Risk"]].mean()

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Risk
Group,,,,,
Business,"44,633.33","75,083.33","43,566.67","147,525.00","103,958.33"
HASS,"37,186.36","62,968.18","34,145.45","129,363.64","95,218.18"
STEM,"53,862.50","90,812.50","56,025.00","157,625.00","101,600.00"